import {
  Footprints, IdCard, Smartphone, Link2,
  Wallet, Handshake,
  ArrowBigRight, ArrowUpCircle, Timer,
  Ruler,
  Repeat, CircleDashed,
  ThumbsUp, Trees, Lock,
  Droplets, Clock, FlagTriangleRight,
  Wrench, Unlock, PhoneCall,
  Globe, MapPinned,
  User, Ban, Users,
  Hand, ShieldAlert, Zap,
} from "lucide-react";

// Sourced from DogsCBR's existing "OHS Program Test" Google Form + OHS Guidelines doc.
// Every correct answer and hint is a direct paraphrase of the official OHS Guidelines,
// so the quiz stays a faithful (just friendlier) version of the real vetting test.
// `render` picks the visual treatment in Quiz.jsx: "backpack" (drag-to-pack) or
// "tiles" (big icon cards) — every option carries an `icon` for the tile view.
export const quizQuestions = [
  {
    id: "bring",
    prompt: "Drag what you need into the backpack before heading out.",
    type: "multi",
    render: "backpack",
    options: [
      { id: "shoes", label: "Enclosed shoes", icon: Footprints },
      { id: "id", label: "Photo ID", icon: IdCard },
      { id: "phone", label: "Phone", icon: Smartphone },
      { id: "leash", label: "Spare leash", icon: Link2 },
    ],
    correct: ["shoes", "id", "phone"],
    hint: "🐾 I need you prepared! Enclosed shoes so we can keep pace, ID to sign me out, and a phone in case you need to call for backup.",
  },
  {
    id: "id-handling",
    prompt: "What should you do with your photo ID before starting a walk?",
    type: "single",
    render: "tiles",
    options: [
      { id: "keep", label: "Keep it with you during the walk", icon: Wallet },
      { id: "hand", label: "Hand it to staff, collect it when you return", icon: Handshake },
    ],
    correct: ["hand"],
    hint: "🐾 Hand your ID to staff before we go — they'll give it back the second you bring me home safe.",
  },
  {
    id: "pulling",
    prompt: "The dog is pulling you somewhere you don't want to go. What do you do?",
    type: "single",
    render: "tiles",
    options: [
      { id: "tug", label: "Tug the lead to redirect them", icon: ArrowBigRight },
      { id: "carry", label: "Pick the dog up and carry it", icon: ArrowUpCircle },
      { id: "wait", label: "Stand your ground, don't tug", icon: Timer },
    ],
    correct: ["wait"],
    hint: "🐾 If I get a little excited, just stand your ground gently — no tugging. I'll settle down.",
  },
  {
    id: "distance",
    prompt: "How far away from other dogs should you stay?",
    type: "single",
    render: "tiles",
    options: [
      { id: "5", label: "Less than 5 metres", icon: Ruler },
      { id: "5-10", label: "5–10 metres", icon: Ruler },
      { id: "10", label: "At least 10 metres", icon: Ruler },
      { id: "any", label: "Doesn't matter", icon: Ban },
    ],
    correct: ["10"],
    hint: "🐾 Please keep at least 10 metres between me and other dogs — not everyone's ready to be my best friend yet.",
  },
  {
    id: "lead-hold",
    prompt: "How should you hold the lead?",
    type: "single",
    render: "tiles",
    options: [
      { id: "wrap", label: "Wrap the entire lead around your hand", icon: Repeat },
      { id: "loop", label: "Hand through the loop, grip the lead", icon: Link2 },
      { id: "loop-only", label: "Only grab the loop, nothing else", icon: CircleDashed },
    ],
    correct: ["loop"],
    hint: "🐾 Loop my lead securely around your wrist, then grip it — never just hold the loop alone.",
  },
  {
    id: "detach",
    prompt: "When can you take the lead off the dog?",
    type: "single",
    render: "tiles",
    options: [
      { id: "good", label: "When the dog is being well behaved", icon: ThumbsUp },
      { id: "park", label: "When in a park or open space", icon: Trees },
      { id: "never", label: "Never — don't detach it", icon: Lock },
    ],
    correct: ["never"],
    hint: "🐾 Please never take my lead or harness off mid-walk — if something feels loose, come find a staff member with me.",
  },
  {
    id: "water",
    prompt: "On a 60+ minute walk, how often should you offer the dog water?",
    type: "single",
    render: "tiles",
    options: [
      { id: "5m", label: "Every 5 minutes", icon: Timer },
      { id: "30m", label: "Every 30 minutes", icon: Droplets },
      { id: "1h", label: "Every hour", icon: Clock },
      { id: "end", label: "Once the walk is finished", icon: FlagTriangleRight },
    ],
    correct: ["30m"],
    hint: "🐾 On our longer walks (60+ minutes), I get thirsty — offer me water every 30 minutes.",
  },
  {
    id: "harness",
    prompt: "You notice the dog's harness feels loose. What do you do?",
    type: "single",
    render: "tiles",
    options: [
      { id: "self-fix", label: "Try to secure it yourself", icon: Wrench },
      { id: "remove", label: "Remove it to tighten", icon: Unlock },
      { id: "staff", label: "Contact a DogsCBR staff member", icon: PhoneCall },
    ],
    correct: ["staff"],
    hint: "🐾 Please don't try to fix my harness yourself — go find a DogsCBR staff member.",
  },
  {
    id: "where",
    prompt: "Where are you allowed to walk the dog?",
    type: "single",
    render: "tiles",
    options: [
      { id: "anywhere", label: "Anywhere you like", icon: Globe },
      { id: "approved", label: "Public areas and approved routes", icon: MapPinned },
    ],
    correct: ["approved"],
    hint: "🐾 Let's stick to public areas or DogsCBR's favourite walking routes together.",
  },
  {
    id: "minors",
    prompt: "Can someone under 18 walk a dog?",
    type: "single",
    render: "tiles",
    options: [
      { id: "yes", label: "Yes, on their own", icon: User },
      { id: "no", label: "No", icon: Ban },
      { id: "adult", label: "Yes, with an accompanying adult member", icon: Users },
    ],
    correct: ["adult"],
    hint: "🐾 If you're under 18, bring a grown-up Community Member along and share my lead with them the whole time.",
  },
  {
    id: "eating",
    prompt: "The dog tries to eat something off the ground. What do you do?",
    type: "single",
    render: "tiles",
    options: [
      { id: "grab", label: "Grab it from the dog's mouth", icon: Hand },
      { id: "move", label: "Gently move the dog away, contact staff", icon: ShieldAlert },
      { id: "tug", label: "Forcefully tug the dog away", icon: Zap },
    ],
    correct: ["move"],
    hint: "🐾 If I try to snack on something sketchy, gently steer me away and call staff — please don't wrestle it from my mouth.",
  },
];
